CREATE TABLE antoine_properties
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    substance_name VARCHAR(255) NOT NULL,
    a_coefficient    DOUBLE PRECISION NOT NULL,
    b_coefficient    DOUBLE PRECISION NOT NULL,
    c_coefficient    DOUBLE PRECISION NOT NULL,
    min_temperature  DOUBLE PRECISION,
    max_temperature  DOUBLE PRECISION,
    boiling_enthalpy DOUBLE PRECISION,
        CONSTRAINT fk_substance
        FOREIGN KEY (substance_name)
        REFERENCES substance (name) ON DELETE CASCADE
);